### ISSUE TITLE
Como passar os parâmetros

### ISSUE THREAD

**Issue by zottis** [adrianosantostreina/ADRConnection#4]
Olá,  achei fantástico o ADRConnection.
mas estou me batendo com uma situação:
Passei um SQL com parametro e ele não reconhece o mesmo.
Como é feito isso?
**O SQLestá assim**
vSQL = 'SELECT first(50) c.COD_CLIENTE cd_cliente, '+
         '                  C.Razao_Social ds_razaosocial '+
        '              From Clientes C '+
        '             Where c.DELETADO  = ''N'' '+
        '               and c.bloqueado = ''N'' '+
        '               and c.data_atualizacao >= :varDataAtualizacao '+
        '             Order by c.Cod_CLIENTE';
        **No Dataset faço assim:**
          LDataSet :=  FQuery
                        .SQL(vSQL)
                        .ParamAsDate('varDataAtualizacao',vData)
                        .Open;

**Comment by gabrielbaltazar** [comment]
Bom dia.
Seria algo assim
![DataSet](https://user-images.githubusercontent.com/9014016/167859729-6bd34e47-2ead-4dc6-ab19-dddda34d9f1a.png)
